version: '3'
services:
  prisma:
    build: .
    restart: always
    depends_on:
      - "cs-postgres"
    ports:
      - '4466:4466'
    environment:
      SLOW_QUERIES_LOGGING: 'true'
      SLOW_QUERIES_LOGGING_THRESHOLD: 0
  cs-postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: creators_gate_psql_00
      POSTGRES_DB: database
volumes:
  db_data:

